---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: emqx-cluster
  namespace: default
spec:
  releaseName: emqx-cluster
  url: https://github.com/emqx/emqx-rel/deploy/charts/emqx
  ref:
    branch: master
  values:
    service:
      type: NodePort