---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: emqx-cluster
  namespace: default
spec:
  git: https://github.com/emqx/emqx-rel/tree/master/deploy
  path: charts/emqx
  values:
    service:
      type: NodePort