---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: emqx-cluster
  namespace: default
spec:
  interval: 1m
  url: https://github.com/emqx/emqx-rel/tree/master/deploy/charts/emqx
  values:
    service:
      type: NodePort