---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: emqx-cluster
  namespace: default
spec:
  releaseName: emqx-cluster
  chart:
    repository: https://github.com/emqx/emqx-rel/deploy/
    path: charts/emqx
  values:
    service:
      type: NodePort